apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: payment
data:
  CART_HOST: cart
  CART_PORT: "8080"
  USER_HOST: user
  USER_PORT: "8080"
  AMQP_HOST: rabbitmq
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: payment
spec: 
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: payment
  template:
    metadata:
      name: payment
      labels:
        project: roboshop
        tier: db
        component: payment
    spec:
      containers:
        - name: payment
          image: happielearning/payment:1.4.0
          imagePullPolicy: Always # safe to pull everytime. There may images which are fixed and pushed with same build version
          resources:
            requests:
              cpu: "150m"
              memory: "150Mi"
            limits:
              cpu: "150m"
              memory: "150Mi"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 2

          envFrom:
          - configMapRef:
              name: payment

---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    # labels are used for selector
    project: roboshop
    tier: db
    component: payment
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port
