apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: shipping
data:
  CART_ENDPOINT: cart:8080
  DB_HOST: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: shipping
spec: 
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: shipping
  template:
    metadata:
      name: shipping
      labels:
        project: roboshop
        tier: db
        component: shipping
    spec:
      containers:
        - name: shipping
          image: happielearning/shipping:1.4.0
          imagePullPolicy: Always # safe to pull everytime. There may images which are fixed and pushed with same build version
          resources:
            requests:
            #   cpu: "100m"
            #   memory: "150Mi"
            # limits:
            #   cpu: "100m"
            #   memory: "150Mi"
          startupProbe:
            httpGet:
              port: 8080
            periodSeconds: 10
            failureThreshold: 20
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 2

          envFrom:
          - configMapRef:
              name: shipping

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    # labels are used for selector
    project: roboshop
    tier: db
    component: shipping
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port
