apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: user
data:
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongo:27017/users"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: user
spec: 
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: user
  template:
    metadata:
      name: user
      labels:
        project: roboshop
        tier: db
        component: user
    spec:
      containers:
        - name: user
          image: happielearning/user:1.4.0
          envFrom:
          - configMapRef:
              name: user

---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    # labels are used for selector
    project: roboshop
    tier: db
    component: user
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port
